### ISSUE TITLE
Error at dataset download link

### ISSUE THREAD

**Issue by zpc-whu** [NeBula-Autonomy/nebula-multirobot-dataset#1]
The nextcloud shows
"Unable to create 'data' directory
This can usually be fixed by giving the web server write access to the root directory. See https://docs.nextcloud.com/server/24/go.php?to=admin-dir_permissions"

**Comment by yunzc** [comment]
Thanks for pointing this out! We are working on fixing the problem with the server.

**Comment by yunzc** [comment]
link should be updated!
